# Maintained via
# echo "1.2.3.4 BAD" >> /mesonet/blocklist.txt
# httxt2dbm -i /mesonet/blocklist.txt -o /mesonet/blocklist.map

RewriteEngine On
RewriteOptions InheritDownBefore
RewriteMap ip_blocklist "dbm:/mesonet/blocklist.map"
RewriteCond ${ip_blocklist:%{REMOTE_ADDR}|OK} "BAD"
RewriteRule ^ https://iowamesonet.github.io/sorry/?mode=blocked [R,L]
