# Maintained via
# echo "1.2.3.4 BAD" >> /etc/httpd/conf.d/blocklist.txt
# httxt2dbm -i /etc/httpd/conf.d/blocklist.txt -o /etc/httpd/conf.d/blocklist.map

RewriteEngine On
RewriteOptions InheritDownBefore
RewriteMap ip_blocklist "dbm:/etc/httpd/conf.d/blocklist.map"
RewriteCond ${ip_blocklist:%{REMOTE_ADDR}|OK} "BAD"
RewriteRule ^ https://iowamesonet.github.io/sorry/?mode=blocked [R,L]
