# Modern apache can send direct to syslog via C calls
# This avoids the pipe logger, which was emitting strange gzip errors in prod.
ErrorLog syslog:local1:notice
ErrorLogFormat "[%-m:%l] %V [%{c}a, %a] %M"
