# This is the Apache server configuration file for providing FastCGI support
# through mod_fcgid
#
# Documentation is available at
# http://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html

# Use FastCGI to process .fcg .fcgi & .fpl scripts
AddHandler fcgid-script fcg fcgi fpl

# Sane place to put sockets and shared memory file
FcgidIPCDir /run/mod_fcgid
FcgidProcessTableFile /run/mod_fcgid/fcgid_shm

# 1. PassEnv appears to not work in this case
# 2. Attempting to stabilize segfaults on mapserv exit (suspect GDAL)
FcgidInitialEnv PROJ_LIB "/opt/miniconda3/envs/prod/share/proj"
FcgidInitialEnv CPL_DEBUG "OFF"
FcgidInitialEnv CPL_LOG "/dev/null"
FcgidInitialEnv GDAL_DISABLE_READDIR_ON_OPEN "EMPTY_DIR"

# Set max requests as a safety for run-away memory
FcgidMaxRequestsPerProcess 20000
